### ISSUE TITLE
Code review for commit a58ec

### ISSUE THREAD

**Issue by nicolargo** [nicolargo/pyadl#1]
Hi @hunasdf 

here are my remarks concerning this first commit:

- [x] Around the adl_api.py file, it will be nice to create a global class Adl(object) with some simples method: __init__, adlDeviceGetName, adlDeviceGetMemoryInfo, adlDeviceGetUtilizationRates (for process %), adlDeviceGetTemperature, adlDeviceGetFanSpeed...
- [x] The __init__ should raise exceptions if no AMD/ATI card are detected or if the ADL Lib is not available (or not up to date)
- [x] The Adl class should be added to the __all__ list in the pyadl.py script (only this class with be used by end user)
- [ ] Additionaly create an unitary test script  (with fake data in order to be ran on server without GPU)   
- [x] Unitest should be ran on both Python 2.7+ or Python 3.3+
- [x] In the Author file, add your name and also  Gergo Szabo <szager88@gmail.com>

Great job indead !

**Comment by hunasdf** [comment]
@nicolargo Thanks! I will do it :)

**Comment by hunasdf** [comment]
@nicolargo I updated the code!

**Comment by nicolargo** [comment]
@hunasdf On my machine, i have the following error (with both Python 2 and 3):

```
$ ▶ ipython2
Python 2.7.12 (default, Nov 20 2017, 18:23:56) 
Type "copyright", "credits" or "license" for more information.

IPython 5.3.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import pyadl
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-1-341ca56346c9> in <module>()
----> 1 import pyadl

/home/nicolargo/Dropbox/dev/pyadl/pyadl/__init__.py in <module>()
      9 # Add:
     10 # from pyadl import <list of classes of the __all__ variable
---> 11 from .pyadl import *

/home/nicolargo/Dropbox/dev/pyadl/pyadl/pyadl.py in <module>()
     25 try:
     26         from .adl_api import *
---> 27 except (OSError, WindowsError):
     28         raise ADLError("Driver not found!")
     29 # RuntimeError raises from adl_api if OS not supported

NameError: name 'WindowsError' is not defined

In [2]: exit
```

As said here (https://lists.gt.net/python/dev/788768): "WindowsError is for Windows-specific errors (hence the name!). You shouldn't rely on it being defined on non-Windows machines."
==> WindowsError subclasses OSError, so i have change the code to only use OSError.

I patch this:

```
$ ▶ ipython2
Python 2.7.12 (default, Nov 20 2017, 18:23:56) 
Type "copyright", "credits" or "license" for more information.

IPython 5.3.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import pyadl
---------------------------------------------------------------------------
ADLError                                  Traceback (most recent call last)
<ipython-input-1-341ca56346c9> in <module>()
----> 1 import pyadl

/home/nicolargo/Dropbox/dev/pyadl/pyadl/__init__.py in <module>()
      9 # Add:
     10 # from pyadl import <list of classes of the __all__ variable
---> 11 from .pyadl import *

/home/nicolargo/Dropbox/dev/pyadl/pyadl/pyadl.py in <module>()
     26         from .adl_api import *
     27 except OSError:
---> 28         raise ADLError("Driver not found!")
     29 # RuntimeError raises from adl_api if OS not supported
     30 

ADLError: Driver not found!
```

Much better :)

Can you please show me the output of the following command (the goal is to have the type and an output example that i can use for my test when i will include the lib in Glances):

```
python
>>> import pyadl
>>> i = ADLManager.getInstance()
>>> i
>>> devices = i.getDevices()
>>> devices
>>> for device in devices:
>>>     device.getCurrentCoreVoltage()
>>>     device.getCurrentEngineClock()
>>>     device.getCurrentFanSpeed()
>>>     device.getCurrentMemoryClock()
>>>     device.getCurrentTemperature() 
>>>     device.getCurrentUsage()
>>>     device.getCoreVoltageRange()
>>>     device.getEngineClockRange()
>>>     device.getFanSpeedRange()
>>>     device.getMemoryClockRange()
```

Please also note that you have to configure the Python indentation of your IDE with space (4) instead of tab...

I just publish a patch (0aa69e8) for the WindowsError and space versus tab...

**Comment by hunasdf** [comment]
@nicolargo Thanks for the correction! I am new in the "Python world", sorry for it :)
I found a little typing mistake (mine). I corrected it, so first please, pull the modification.
I added a Usage section to the Readme, but.... Can I format somehow?

The import does not work for me, so I changed to "from pyadl import *". Did I something wrong?! And device.getCurrentFanSpeed() and device.getFanSpeedRange() need a speedType parameter, because the result value based on the unit (percentage or rpm). So, the output:

```
Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyadl import *
>>> i = ADLManager.getInstance()
>>> i
<pyadl.pyadl.ADLManager object at 0x0000000002AC39B0>
>>> devices = i.getDevices()
>>> devices
[<pyadl.pyadl.ADLDevice object at 0x0000000002FE3AC8>]
>>> for device in devices:
...     device.getCurrentCoreVoltage()
...     device.getCurrentEngineClock()
...     device.getCurrentFanSpeed(ADL_DEVICE_FAN_SPEED_TYPE_PERCENTAGE)
...     device.getCurrentFanSpeed(ADL_DEVICE_FAN_SPEED_TYPE_RPM)
...     device.getCurrentMemoryClock()
...     device.getCurrentTemperature()
...     device.getCurrentUsage()
...     device.getCoreVoltageRange()
...     device.getEngineClockRange()
...     device.getFanSpeedRange(ADL_DEVICE_FAN_SPEED_TYPE_PERCENTAGE)
...     device.getFanSpeedRange(ADL_DEVICE_FAN_SPEED_TYPE_RPM)
...     device.getMemoryClockRange()
...
-2077376128
980.97
69
3101
1400.0
77.0
100
(0.0, 0.0)
(150.0, 1200.0)
(0, 100)
(0, 6000)
(75.0, 1750.0)
```

Ps.: The voltage methods always return strange values for me for all devices...

**Comment by nicolargo** [comment]
Thanks, so if i understand correctly, if i want to have the number of devices:

    len(ADLManager.getInstance().getDevices())

For the device name i should use (for the first device):

    d = ADLManager.getInstance().getDevices()
    d[0].adapterName

But what method should i use to have the information needed by the Glances GPU plugin:

- Process consumption in % ?
- Memory consumption in % ?

**Comment by nicolargo** [comment]
PS: i just update the README file with correct markdown (see doc here: https://guides.github.com/features/mastering-markdown/).

PS2: Your Python code is very nice to read :+1:

**Comment by hunasdf** [comment]
Correct for the number of device and adapter's name. Do I create a method, which return a number of device? For example `ADLManager.getInstance().numberOfDevices()`
For the process consumption you can use `device.getCurrentUsage()`. Its returns an integer and the "unit" is percentage. But for the memory... I do not found any method to grab this information. Only on linux, there is a "ADL2_Adapter_MemoryInfo_Get" method, but also not return the memory usage, only the memory size, type and bandwidth. I checked the APIs and examples, but nothing. Only the current frequency and the range.
Thanks for the guide, what is what i am looking for! :)

**Comment by nicolargo** [comment]
Ok for the ADLManager.getInstance().numberOfDevices() !

In your example, the process consumption always return 100 (%). Is it a normal behavior ? 

For the memory it is a problem... The Glances Nvidia plugin shows this information (per device):

![image](https://user-images.githubusercontent.com/776747/34408376-d3f0c686-ebc3-11e7-92a7-2ad26381db7b.png)

What is relevant in term of memory when you monitor a GPU device ?

**Comment by hunasdf** [comment]
Yes, 100% is absolutely correct in my case, because the mining software is running. Here the output after i stopped it
```
python test.py -s
0. AMD Radeon (TM) R9 380 Series
        Engine core voltage: -2076327552 mV (0.0 mV - 0.0 mV)
        Engine clock: 300.0 MHz (150.0 MHz - 1200.0 MHz)
        Memory clock: 150.0 MHz (75.0 MHz - 1750.0 MHz)
        Fan speed: 31 % (0 % - 100 %)
        Fan speed: 1524 RPM (0 RPM - 6000 RPM)
        Temperature: 53.0 Celsius
        Usage: 0 %
```

For the memory, I have not known yet... I looked around on the internet too, maybe the solution will OpenCL

**Comment by nicolargo** [comment]
Ok, if you are agree, i am going to release the first version of PyADL and starts the integration in Glances. I a currently working on a big refactor of the plugins and export command line. I will start working on the AMD/ATI GPU plugin after.

**Comment by hunasdf** [comment]
it is okay for me!

**Comment by nicolargo** [comment]
I just upload the version 0.1 of PyADL to the Pypi repository: https://pypi.python.org/pypi/pyadl/0.1

Can you install and test it on your system ?

```
pip install --user pyadl
```

Then test the lib...

**Comment by hunasdf** [comment]
I used the same test.py as in the repo and it looks good
```
C:\Users\Miner1\Documents\pipPyADL>dir
 Volume in drive C has no label.
 Volume Serial Number is 36C1-4B7E

 Directory of C:\Users\Miner1\Documents\pipPyADL

12/29/2017  10:26 AM    <DIR>          .
12/29/2017  10:26 AM    <DIR>          ..
12/29/2017  10:26 AM             4,074 test.py
               1 File(s)          4,074 bytes
               2 Dir(s)   2,677,587,968 bytes free

C:\Users\Miner1\Documents\pipPyADL>python test.py -s
0. AMD Radeon (TM) R9 380 Series
        Engine core voltage: -322637440 mV (0.0 mV - 0.0 mV)
        Engine clock: 979.99 MHz (150.0 MHz - 1200.0 MHz)
        Memory clock: 1400.0 MHz (75.0 MHz - 1750.0 MHz)
        Fan speed: 59 % (0 % - 100 %)
        Fan speed: 2698 RPM (0 RPM - 6000 RPM)
        Temperature: 75.0 Celsius
        Usage: 100 %
```

**Comment by Silverwaffen** [comment]
c:\\pyadl-master>python test.py -s
It what i got. J'aimerais bien l'ajouter à Glance !!!!
0. Radeon RX 580 Series
        Engine core voltage: 969405440 mV (0.0 mV - 0.0 mV)
        Engine clock: 1329.75 MHz (150.0 MHz - 2000.0 MHz)
        Memory clock: 2000.0 MHz (150.0 MHz - 2250.0 MHz)
        Fan speed: 100 % (0 % - 100 %)
        Fan speed: 2257 RPM (0 RPM - 2400 RPM)
        Temperature: 72.0 Celsius
        Usage: 100 %

16. Radeon RX 580 Series
        Engine core voltage: 1 mV (0.0 mV - 0.0 mV)
        Engine clock: 1348.42 MHz (150.0 MHz - 2000.0 MHz)
        Memory clock: 1750.0 MHz (150.0 MHz - 2250.0 MHz)
        Fan speed: 50 % (0 % - 100 %)
        Fan speed: 2361 RPM (0 RPM - 4500 RPM)
        Temperature: 65.0 Celsius
        Usage: 11 %

32. Radeon RX 580 Series
        Engine core voltage: 1 mV (0.0 mV - 0.0 mV)
        Engine clock: 1344.05 MHz (150.0 MHz - 2000.0 MHz)
        Memory clock: 1750.0 MHz (150.0 MHz - 2250.0 MHz)
        Fan speed: 61 % (0 % - 100 %)
        Fan speed: 2305 RPM (0 RPM - 3200 RPM)
        Temperature: 72.0 Celsius
        Usage: 100 %

48. Radeon RX 560 Series
        Engine core voltage: 1 mV (0.0 mV - 0.0 mV)
        Engine clock: 1261.27 MHz (110.0 MHz - 1800.0 MHz)
        Memory clock: 1750.0 MHz (150.0 MHz - 2000.0 MHz)
        Fan speed: 50 % (0 % - 100 %)
        Fan speed: 1676 RPM (0 RPM - 3600 RPM)
        Temperature: 65.0 Celsius
        Usage: 100 %
